# 넘파이 

In [1]:
import numpy as np
 # help 함수 적극 활용!

1. array 정보 확인하기
  
np.array  
array.shape  
array.ndim  
array.dtype  
array.astype

In [4]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3], [4, 5, 6]])

# 넘파이 array데이터 타입 --> numpy.ndarray
# array 형태 출력 / array_name.shape
print('type:', type(array1))
print('shape:', array1.shape)
print('shape:', array2.shape)

type: <class 'numpy.ndarray'>
shape: (3,)
shape: (2, 3)


In [6]:
# 차원 array_name.ndim
print(f'array1: {0}차원\narray2: {1}차원\n', array1.ndim, array2.ndim)

# array 요소들 dtype 통일됨
# 요소 데이터 타입 / array_name.dtype
# 요소 데이터 타입 바꾸기 / array_name.astype('int32') etc...

array1: 0차원
array2: 1차원 1 2


2. ndarray 생성하기

np.arrange(10)  
np.zeros((3, 2), dtype='int32')  
np.ones((3, 2), dtype='int32')

In [17]:
# 1차원 배열 n개 원소 생성 / np.arange(n)
array1 = np.arange(10)
print(array1)

# np.zeros((), dtype = '?)' / 원소 0인 배열 생성 
# np.ones((,), dtype = '?') / 원소 1인 배열 생성
array2 = np.zeros((3, 3, 3), dtype='int32')
array3 = np.ones((2, 3))
print('array2 = \n', array2, '\n\n','array3 = \n', array3)

[0 1 2 3 4 5 6 7 8 9]
array2 = 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]] 

 array3 = 
 [[1. 1. 1.]
 [1. 1. 1.]]


3. ndarray 변환하기  
np.reshape()  
np.tolist()

In [21]:
array_re = array2.reshape(9, 3)
print(array_re)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [20]:
# -1은 크기에 알맞게 값을 조정하하는 뜻임
array_re = array2.reshape(-1, 3)
print(array_re)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


5. ndarray 인덱싱
- 단일값추출
- 슬라이싱
- 팬시 인덱싱
- 불린 인덱싱

In [28]:
# 특이한거만 다루겠음 
array1 = np.arange(1, 28)
array1 = array1.reshape(3, 3, 3)
print(array1, '\n')

# 팬시 인덱싱(사실 잘모르게ㅖㅆ음)
print(array1[[1, 2], [1, 2]], '\n')

# 불린 인덱싱
print(array1[array1 > 9])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] 

[[13 14 15]
 [25 26 27]] 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27]


6. ndarray 정렬  
np.sort()  
np.argsort()

In [4]:
# np.sort / 정렬 호출, 기존 array에는 변화 x
messy_array = np.array([1, 3, 2, 4])
clean_array = np.sort(messy_array)
print(clean_array)
print(messy_array, '\n')

# array_name.sort()/ 정렬 호출 x, 기존 array 정렬 반환
clean_array_2 = messy_array.sort()
print(clean_array_2)
print(messy_array)

[1 2 3 4]
[1 3 2 4] 

None
[1 2 3 4]


#### axis 간단 정리  
axis == 축, axis가 작을 수록 더 작은 차원의 축 지정 
  
ex) 2차원 ndarray  
[[1, 2], [3, 4]]  
axis = 0 | [1, 2] --> [3, 4] 바깥쪽 괄호, row를 나타냄  
axis = 1 | 1 --> 2, 3 --> 4 안쪽 괄호, column을 나타냄  

In [7]:
# np.argsort(ndarray) / 각 index의 크기 순위를 매김
messy_array = np.array([1, 3, 2, 4])
arg_array = np.argsort(messy_array)
print(arg_array)



[0 2 1 3]


In [9]:
# argsort 활용 예시
name = np.array(['kim', 'lee', 'chu'])
score = np.array([30, 20, 100])
ranking = np.argsort(score)
print(name[ranking])
# wow

['lee' 'kim' 'chu']


#### 7. dot production / transpose
np.dot(A, B) --> 행렬 곱
np.transpose(A) --> 전치행렬

In [3]:
A = np.array([[1, 2, 3], 
              [4, 5, 6]])
B = np.array([[1, 2], 
              [3, 4], 
              [5, 6]])
dot_product = np.dot(A, B)
transpose_matrix = np.transpose(A)
print(dot_product, '\n')
print(transpose_matrix)

[[22 28]
 [49 64]] 

[[1 4]
 [2 5]
 [3 6]]
